# Generated by Django 5.0.2 on 2024-02-14 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='user',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.client', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.message', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='logs',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message'),
        ),
        migrations.AddConstraint(
            model_name='logs',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('response__isnull', False), ('status', False)), ('status', True), _connector='OR'), name='not_empty_response_on_failure'),
        ),
    ]
